---
title: "Lab3_RegularExpressions"
author: "Daniel Penados-Richter"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Ex.1

The expression is: ```\s{2,}``` where ```\s``` would look for spaces and ```{2,}``` would for 2 o more of the characters previous mention. 2 or more to omit the space between first string. Lastly, you just place with a comma. 



Ex. 2:

So the reg. expression is ```(\w*), (\w*), (\S.*)``` This will select last name, name, and institution  as a individual group. Finally I will replace with ```\2 \1 (\3)```. This will change the order for Name Last Name and finally add parenthesis to the institution. 


Ex. 3. 
This was pretty simple. Just look for ```.mp3\s``` and replace with ```.mp3\n``` this will delete the space, and create a new line after the .mp3

Ex. 4. 

The expression is: ```(\d*) (.*).mp3```. ```(\d*)``` will select the digits ```(.*).mp3``` this will select everything else. Replace with ```\2_\1.mp3```. This will reorder. The words first, the digits separated by a "_", and add the .mp3

Ex.5

The expression is: ```(\w)\w+,(\w*),(\d*\.\d),(\d*)```. ```(\w)\w+,``` This will capture the first letter of the first word. ```(\w*)``` this will capture the second word,```(\d*\.\d)``` this will capture the digits before the dot, the dot and the digit after the dot, ```(\d*)``` lastly this will capture the last digit after the comma. Replace with ```\1_\2.\4```, basically add the first object and second separated with "_", and add the fouth separated by a dot. 

Ex. 6

The expression is very similar: ```(\w)\w+,(\w{4})\w+,(\d*\.\d),(\d*)```. The only change is the second group ```(\w{4})\w+``` which is selecting the first 4 digits of the second word. Replace with the same as before. 

Ex. 7

Again, is very similar: ```(\w{3})\w+,(\w{3})\w+,(\d*\.\d),(\d*)```. The main change is select the fist 3 letter of each word: ```(\w{3})\w+,(\w{3})\w+,```. Lastly, just replace with: ```\1\2, \4, \3```. This will join the to first characters, located the 4th separated by a comma, and the 3rd at the end, also separated by a comma. 













